CREATE DATABASE InventoryDB;
USE InventoryDB;

CREATE TABLE users(
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    Password VARCHAR(255),
    Role ENUM("admin","user","manager") NOT NULL

);

CREATE TABLE stock_item (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Price DECIMAL(10,2) NOT NULL,
    Manufacturer VARCHAR(255),
    Product VARCHAR(100) NOT NULL,
    Quantity INT NOT NULL,
    Date_Added DATE NOT NULL,
    Barcode VARCHAR(255),
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);